### PR TITLE
feat: fixed max depth and refactored code

### LINKED ISSUE #2: fix max depth of dependencies logic
Printing the number of max dependencies and the length of the longest dependency chain currently has some problems:

- Running the command consecutively 4-5 times leads to different results
- The length of the longest dependency chain which gets printed in verbose mode doesn't match the length which is present as `maxDepthOfDependencies` in the `analysis.json` file.

The current code for calculating the longest dependency chain is based on [storing the dependency graph](https://github.com/RinkiyaKeDad/dependency-analyzer-poc/blob/master/cmd/analyze_deps.go#L50-L69) and then finding the [longest path in this graph](https://www.geeksforgeeks.org/longest-path-in-a-directed-acyclic-graph-dynamic-programming/).

The logic for the length of the longest dependency chain involves [iterating through each unvisited dependency](https://github.com/RinkiyaKeDad/dependency-analyzer-poc/blob/feat_1/cmd/analyze_deps.go#L96-L100) and performing a [depth first search](https://github.com/RinkiyaKeDad/dependency-analyzer-poc/blob/feat_1/cmd/utils.go#L11-L22) on it and updating the [https://github.com/RinkiyaKeDad/dependency-analyzer-poc/blob/feat_1/cmd/utils.go#L17) each time. To avoid infinite recursion dependencies which have already been visited are [kept track of](https://github.com/RinkiyaKeDad/dependency-analyzer-poc/blob/feat_1/cmd/utils.go#L12). In verbose mode for printing the longest dependency chain also a [visited array](https://github.com/RinkiyaKeDad/dependency-analyzer-poc/blob/feat_1/cmd/analyze_deps.go#L130) is used.

### PR DESCRIPTION
**Pull request by RinkiyaKeDad**
Signed-off-by: RinkiyaKeDad <arshsharma461@gmail.com>

Fixes #2 

Fixed the logic for `maxDepthOfDependencies` and refactored the code to extract stuff into functions :)

### CODE REVIEW

File: cmd/analyze_deps.go [hunk 1]
```diff
@@ -30,99 +27,30 @@ to quickly create a Cobra application.`,
...
 		// get values
-		totalDeps := len(deps) - 1 // -1 for main module name
-		maxDepth := dp[mainModule]
+		totalDeps := len(deps)
+		maxDepth := getMaxDepth(chains)
 		directDeps := len(depGraph[mainModule])
 		transitiveDeps := totalDeps - directDeps
 
+		// print the longest chain
+		if verbose {
```
Comment (alenkacz) [inline cmd/analyze_deps.go:49]: I think this should be printed by default, what do you think?

File: cmd/analyze_deps.go [hunk 2]
```diff
@@ -30,99 +27,30 @@ to quickly create a Cobra application.`,
...
+			fmt.Println("Longest chain is: ")
+			printChain(chains[maxDepth+1])
```
Comment (alenkacz) [inline cmd/analyze_deps.go:53]: hmm why maxDepth + 1? 🤔

File: cmd/analyze_deps.go [hunk 3]
```diff
@@ -30,99 +27,30 @@ to quickly create a Cobra application.`,
...
-				cur = longestPath[cur]
-				// if vis[cur] == true {
-				// 	break
-				// }
-			}
-		}
+		// Get all chains starting from main module
+		chains := make(map[int][]string)
+		var temp []string
+		getChains(mainModule, depGraph, temp, chains)
```
Comment (alenkacz) [inline cmd/analyze_deps.go:40]: would be nicer if getChains returns the chains

File: cmd/utils.go [hunk 4]
```diff
@@ -1,31 +1,112 @@
...
+	return depGraph, deps, mainModule
+}
+
+func printDeps(deps []string) {
+	fmt.Println()
+	for _, dep := range deps {
+		fmt.Println(dep)
 	}
-	recVisited[k] = false
+	fmt.Println()
```
Comment (alenkacz) [inline cmd/utils.go:109]: what is this for?

**Review by alenkacz — APPROVED** [review]
I have couple of nits, otherwise looks good. Would be good to reintroduce the tests at one point :)

File: cmd/analyze_deps.go (hunk 1 above)
Comment (RinkiyaKeDad) [reply cmd/analyze_deps.go:49]: Sounds good! I don't have any particular thoughts on this as of now. I'll make the change, we can always revert back later if needed once we finalize how the tool would be used.
cc @dims

File: cmd/analyze_deps.go (hunk 2 above)
Comment (RinkiyaKeDad) [reply cmd/analyze_deps.go:53]: `maxDepth` stores the length of the chain, so for A -> B -> C `maxDepth` will store 2. Whereas the keys of the map `chains` are the number of actual dependencies present in the chain. So that's why the +1 is needed. I should probably add a comment in the code for future reference 😄

File: cmd/analyze_deps.go (hunk 3 above)
Comment (RinkiyaKeDad) [reply cmd/analyze_deps.go:40]: I also thought of that but got confused a bit. `chains` needs to be kind of like a global variable for the `getChains` function but if I declare it inside `getChains` then I think each time it will get redeclared.

Would using a wrapper function which declares `chains` and then calls `getChains` be ideal? We can then just call this wrapper function in the main code and it will return `chains`.

File: cmd/utils.go (hunk 4 above)
Comment (RinkiyaKeDad) [reply cmd/utils.go:109]: That's just for formatting. I wanted a blank line to be printed after the output in the terminal so that it looks a bit clean 😅
